/*
 * Database
 * 
 * COMP 1020
 * Instructor: Fereshteh Amini
 * Assignment: 2, Question: 1
 * @author     Richard Constantine
 * @version    2016/02/29
 * 
 * Purpose: To save a list generated by the courseListQ2 class and save it in a file.
 */
import java.io.*;
import java.util.Scanner;

public class Database {
  
  // Instance Variables
  private String inputFile;
  private String outputFile;
  
  public Database(String input, String output)
  {
    inputFile = input;
    outputFile = output;
  }//Database
  
  /* 
   * [Database is a default constructor to initialize values]
   * [Input: Receives input from the main method then acts to initalize values stored within
   * the Database object]
   * [Output: N/A]
   * 
   * @param [firstParam: recieves input as a file and assigns this to the appropriate instance variable]
   * @param [secondParam: recieves input as a file and assigns this to the appropriate instance variable]
   * @return [N/A]
   */
  
  public CourseListQ2 load()
  {
    CourseListQ2 courseList = new CourseListQ2();  
    Scanner lineReader = null;

    try 
    {
      lineReader = new Scanner(new File(inputFile));   
      
      Course tempCourse;
      
      
      while(lineReader.hasNextLine())
      {
        String line = lineReader.nextLine();
        String delimiter = ",";
        String[] tokens = line.split(delimiter);
        
        int crn = Integer.parseInt(tokens[0]);
        String title = tokens[1];
        String dept = tokens[2];
        int term = Integer.parseInt(tokens[3]);
        int year = Integer.parseInt(tokens[4]);
        
        try
        {
          tempCourse = new Course(crn, title, dept, term, year);
         
          courseList.addCourse(tempCourse);
        }//try
        catch(Exception e)
        {
          System.out.println(e.getMessage());
        }//catch
        
      }//while
      
      lineReader.close();
    }//try
    
    catch(IOException e)
    {
      System.out.println("Nope. That didn't work: "+e.getMessage());
    }//catch 
    
    return courseList;
  }//CourseListQ2
  
  /* 
   * [load reads the input file from the constructor and creates a course object for each line and stores/
   * returns it in a list object CourseListQ2]
   * [Input: Receives input from the constructor then reads the file line by line]
   * [Output: Returns a list of the courses created from the file]
   * 
   * @param [N/A]
   * @return [object CourseListQ2 containing a list of courses read from a file]
   */
  
  public void save(CourseListQ2 courseList)
  {
    try 
    {
      FileWriter output = new FileWriter(outputFile);
      PrintWriter writeIt = new PrintWriter(output);
      
      int count = 0;
      
      while(count < courseList.getNumCourses())
      {
        Course tempCourse = courseList.getCourse(count);
        
        writeIt.println(tempCourse.toCsv());
        count++;
      }//while
      
      output.close();
      
    }//try
    
    catch(IOException e)
    {
      System.out.println("Nope. That didn't work: "+e.getMessage());
    }//catch  
    
  }//save
  
  /* 
   * [the save method writes data from an object CourseListQ2 to a specified output text file]
   * [Input: Receives input from the main method in the form of a list of courses]
   * [Output: Writes the contents of the list to a text file]
   * 
   * @param [firstParam: Receives an object CourseListQ2 and saves the CRN, title, department, term and year
   * as a comma separated line in a specified output file]
   * @return [N/A]
   */
}//Database